#ifndef GUIDANCE_MODULE_H
#define GUIDANCE_MODULE_H

#include "external/ConcurrentModuleFramework/src/base_module.h"

namespace Onboard {

// The outline for this file was autogenerated
/* Please provide Module Documentation here

*/
class GuidanceModule : public BaseModule {
  public:
    GuidanceModule();
  protected:

    void Poll(std::shared_ptr<ModuleDataCollection> data) override;

};
} // Onboard

#endif