#include "guidance_module.h"
#include "sensor_module.h"
#include <math.h>
#include <iostream>

// The outline for this file was autogenerated by create_new_module.py

void Onboard::GuidanceModule::Init(std::shared_ptr<ModuleDataCollection> data) {
	_module_name = "Guidance Module";
	_module_period_ms = std::chrono::milliseconds(50);

	VectorXd b1d(3);
	b1d << 1, 0, 0;
	_guidance_data.xd = VectorXd::Zero(3);
	_guidance_data.b1d = b1d;
	data->AddModuleData(_guidance_data, "guidance_data");
}

void Onboard::GuidanceModule::Poll(std::shared_ptr<ModuleDataCollection> data) {
	double t = data->GetModuleData<SensorModuleData>("sensor_data").t;

	VectorXd xd(3);
    xd << 10*cos(2*M_PI*0.1*t), 10*sin(2*M_PI*0.1*t), -10;

	_guidance_data.xd = xd;

	data->SetModuleData(_guidance_data, "guidance_data");

}

