#include "navigation_module.h"

#include <eigen3/Eigen/Dense>
#include <math.h>
#include <map>

// The outline for this file was autogenerated by create_new_module.py

namespace Onboard { 
NavigationModule::NavigationModule() {
	_module_name = "navigation_module";
	_module_period_ms = std::chrono::milliseconds(10);


	_module_data.Add<VectorXd>("x", VectorXd::Zero(3));
	_module_data.Add<VectorXd>("v", VectorXd::Zero(3));
	_module_data.Add<MatrixXd>("R", MatrixXd::Identity(3,3));
	_module_data.Add<VectorXd>("W", VectorXd::Zero(3));

}

void NavigationModule::Poll(std::shared_ptr<ModuleDataCollection> data) {
    VectorXd x = data->GetModuleData("sensor_module").Get<VectorXd>("x");
    VectorXd v = data->GetModuleData("sensor_module").Get<VectorXd>("v");
    MatrixXd R = data->GetModuleData("sensor_module").Get<MatrixXd>("R");
    VectorXd W = data->GetModuleData("gyroscope_module").Get<VectorXd>("W");

	_module_data.Set<VectorXd>("x", x);
	_module_data.Set<VectorXd>("v", v);
	_module_data.Set<MatrixXd>("R", R);
	_module_data.Set<VectorXd>("W", W);

}
}
