#include "navigation_module.h"
#include "sensor_module.h"

#include <math.h>
#include <map>

// The outline for this file was autogenerated by create_new_module.py

namespace Onboard { 
void NavigationModule::Init(std::shared_ptr<ModuleDataCollection> data) {
	_module_name = "Navigation Module";
	_module_period_ms = std::chrono::milliseconds(1);

	_navigation_data.x = VectorXd::Zero(3);
	_navigation_data.v = VectorXd::Zero(3);
	_navigation_data.R = MatrixXd::Identity(3,3);
	_navigation_data.W = VectorXd::Zero(3);

	data->AddModuleData(_navigation_data, "navigation_data");

}

void NavigationModule::Poll(std::shared_ptr<ModuleDataCollection> data) {
    VectorXd x = data->GetModuleData<SensorModuleData>("sensor_data").x;
    VectorXd v = data->GetModuleData<SensorModuleData>("sensor_data").v;
    MatrixXd R = data->GetModuleData<SensorModuleData>("sensor_data").R;
    VectorXd W = data->GetModuleData<SensorModuleData>("sensor_data").W;
	_navigation_data.x = x;
	_navigation_data.v = v;
	_navigation_data.R = R;
	_navigation_data.W = W;

	data->AddModuleData(_navigation_data, "navigation_data");

}
}
