load("@rules_cc//cc:defs.bzl", "cc_test", "cc_binary", "cc_library")

cc_library(
    name = "math",
    srcs = [
            ],
    hdrs = [
            "math.h",
            ],
    deps = [
            ],
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
)
