#include "accelerometer_module.h"
#include <chrono>
#include <eigen3/Eigen/Dense>

using Eigen::MatrixXd;
using Eigen::VectorXd;
// The outline for this file was autogenerated by create_new_module.py

namespace Simulation {
AccelerometerModule::AccelerometerModule() {
	_module_name = "accelerometer_module";
	_module_period_ms = std::chrono::milliseconds(5);

	_module_data.Add<VectorXd>("a", VectorXd::Zero(3));
	_module_data.Add<double>("t", 0);
}

void AccelerometerModule::Poll(std::shared_ptr<ModuleDataCollection> data) {
	VectorXd vdot = data->GetModuleData("simulation_module").Get<VectorXd>("vdot");
	double t = data->GetModuleData("simulation_module").Get<double>("t");

	_module_data.Set<VectorXd>("a", vdot);
	_module_data.Set<double>("t", t);

}
}
