#ifndef ACCELEROMETER_MODULE_H
#define ACCELEROMETER_MODULE_H

#include "src/base_module.h"

// The outline for this file was autogenerated
/* Please provide Module Documentation here

*/
namespace Simulation {
class AccelerometerModule : public BaseModule {
  public:

		AccelerometerModule();
  protected:

    void Poll(std::shared_ptr<ModuleDataCollection> data) override;

};
}
#endif