#ifndef GYROSCOPE_MODULE_H
#define GYROSCOPE_MODULE_H

#include <memory>
#include "src/base_module.h"
#include "gyroscope_model.h"

// The outline for this file was autogenerated
/* Please provide Module Documentation here

*/
namespace Simulation {
class GyroscopeModule : public BaseModule {
  public:

		GyroscopeModule();
  protected:

    void Poll(std::shared_ptr<ModuleDataCollection> data) override;

    GyroscopeModel _gyroscope;
};
}

#endif