#ifndef SENSOR_MODULE_H
#define SENSOR_MODULE_H

#include "src/base_module.h"
#include <memory>
#include "gyroscope_model.h"

// The outline for this file was autogenerated
/* Please provide Module Documentation here

*/
namespace Simulation {
class SensorModule : public BaseModule {
  public:

		SensorModule();
  protected:

    void Poll(std::shared_ptr<ModuleDataCollection> data) override;

    GyroscopeModel _gyroscope;

};
}
#endif